#!/usr/bin/env python3
"""
Parse opencode log files and extract LLM requests and responses.

This script parses log files generated by opencode and extracts structured
dictionaries for LLM requests and responses logged in prompt.ts.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any


def extract_json_from_string(s: str, start_pos: int) -> Optional[Tuple[str, int]]:
    """
    Extract a complete JSON object from a string starting at start_pos.
    
    Returns:
        Tuple of (json_string, end_position) or None if not found
    """
    if start_pos >= len(s) or s[start_pos] != '{':
        return None
    
    brace_count = 0
    in_string = False
    escape_next = False
    end_pos = start_pos
    
    for i in range(start_pos, len(s)):
        char = s[i]
        
        if escape_next:
            escape_next = False
            continue
        
        if char == '\\':
            escape_next = True
            continue
        
        if char == '"' and not escape_next:
            in_string = not in_string
            continue
        
        if in_string:
            continue
        
        if char == '{':
            brace_count += 1
        elif char == '}':
            brace_count -= 1
            if brace_count == 0:
                end_pos = i + 1
                return (s[start_pos:end_pos], end_pos)
    
    return None


def parse_log_line(line: str) -> Optional[Dict[str, Any]]:
    """
    Parse a single log line and extract LLM request/response data if present.
    
    Returns:
        Dict with keys: 'type' ('request' or 'response'), 'timestamp', 'data'
        None if line doesn't contain LLM request/response
    """
    line = line.strip()
    if not line:
        return None
    
    # Match log format: LEVEL  TIMESTAMP +DIFFms key=value ... message
    # Example: INFO  2025-11-12T00:02:44 +21ms service=session.prompt session=xxx LLM request {...}
    match = re.match(r'^(DEBUG|INFO|WARN|ERROR)\s+(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})\s+\+\d+ms\s+(.+)$', line)
    if not match:
        return None
    
    level, timestamp_str, rest = match.groups()
    
    # Check if this is an LLM request or response line
    is_request = 'LLM request' in rest
    is_response = 'LLM response' in rest
    
    if not (is_request or is_response):
        return None
    
    # The log format from log.ts: when log.info("LLM request", requestLog) is called,
    # the requestLog object is passed as 'extra'. The build() function iterates over
    # extra entries and creates key=value pairs. Object values are JSON-stringified.
    # So the format is: key1=value1 key2=JSON.stringify(object) ... LLM request
    # 
    # However, since requestLog is a single object passed as extra, it gets iterated
    # and each property becomes a key=value pair. Nested objects/arrays get JSON-stringified.
    # 
    # Strategy: Find all JSON objects in the line and identify the one that contains
    # our request/response data (has sessionID and messageID)
    
    json_data = None
    
    # Find all potential JSON objects in the line
    # Look for patterns like: key={"json":"data"} or standalone {"json":"data"}
    for i, char in enumerate(rest):
        if char == '{':
            result = extract_json_from_string(rest, i)
            if result:
                json_str, _ = result
                try:
                    test_data = json.loads(json_str)
                    # Check if this looks like our request/response data
                    # Request has: sessionID, messageID, model, providerID, system, messages, etc.
                    # Response has: sessionID, messageID, role, mode, tokens, cost, parts
                    if isinstance(test_data, dict) and 'sessionID' in test_data and 'messageID' in test_data:
                        # Additional validation: requests have 'messages', responses have 'parts'
                        if is_request and 'messages' in test_data:
                            json_data = test_data
                            break
                        elif is_response and 'parts' in test_data:
                            json_data = test_data
                            break
                        # Fallback: if it has sessionID and messageID, it's probably our data
                        elif json_data is None:
                            json_data = test_data
                except json.JSONDecodeError:
                    continue
    
    if json_data is None:
        return None
    
    # Parse timestamp
    try:
        timestamp = datetime.fromisoformat(timestamp_str)
    except ValueError:
        timestamp = None
    
    return {
        'type': 'request' if is_request else 'response',
        'level': level,
        'timestamp': timestamp.isoformat() if timestamp else timestamp_str,
        'data': json_data
    }


def parse_log_file(log_path: Path) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Parse a log file and extract all LLM requests and responses.
    
    Args:
        log_path: Path to the log file
        
    Returns:
        Tuple of (requests, responses) where each is a list of dictionaries
    """
    requests = []
    responses = []
    
    if not log_path.exists():
        print(f"Error: Log file not found: {log_path}", file=sys.stderr)
        return requests, responses
    
    with open(log_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            try:
                parsed = parse_log_line(line)
                if parsed:
                    if parsed['type'] == 'request':
                        requests.append(parsed)
                    else:
                        responses.append(parsed)
            except Exception as e:
                print(f"Warning: Error parsing line {line_num}: {e}", file=sys.stderr)
                continue
    
    return requests, responses


def main():
    """Main entry point for the script."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Parse opencode log files and extract LLM requests and responses'
    )
    parser.add_argument(
        'log_file',
        type=Path,
        help='Path to the log file to parse'
    )
    parser.add_argument(
        '--output',
        type=Path,
        help='Output file path (default: print to stdout as JSON)'
    )
    parser.add_argument(
        '--format',
        choices=['json', 'pretty'],
        default='pretty',
        help='Output format: json (compact) or pretty (formatted JSON)'
    )
    parser.add_argument(
        '--requests-only',
        action='store_true',
        help='Only output requests'
    )
    parser.add_argument(
        '--responses-only',
        action='store_true',
        help='Only output responses'
    )
    
    args = parser.parse_args()
    
    # Parse the log file
    requests, responses = parse_log_file(args.log_file)
    
    # Prepare output data
    output_data = {}
    if not args.responses_only:
        output_data['requests'] = requests
    if not args.requests_only:
        output_data['responses'] = responses
    
    # Add summary
    output_data['summary'] = {
        'total_requests': len(requests),
        'total_responses': len(responses),
        'log_file': str(args.log_file)
    }
    
    # Format output
    if args.format == 'pretty':
        output_json = json.dumps(output_data, indent=2, ensure_ascii=False)
    else:
        output_json = json.dumps(output_data, ensure_ascii=False)
    
    # Write output
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(output_json)
        print(f"Parsed {len(requests)} requests and {len(responses)} responses")
        print(f"Output written to: {args.output}")
    else:
        print(output_json)


if __name__ == '__main__':
    main()

